### PR TITLE
Fix default output

### LINKED ISSUE #185: Agent builder does not respect WithDefaultOutput
The agent builder has a method called `WithDefaultOutput`, which allows for specifying an output operator that will be attached to the end of a linear pipeline. This is currently not working as intended.

Expectation:
A pipeline with operators `A -> B` and default output `C`, should produce `A -> B -> C`

Result:
Currently, `B` is not connected to `C`

### PR DESCRIPTION
**Pull request by Mrod1598**
Resolves #185

### CODE REVIEW

File: agent/builder_test.go [hunk 1]
```diff
@@ -36,6 +60,29 @@ func TestBuildAgentSuccess(t *testing.T) {
...
+			require.Equal(t, "$.fake", ops[1].GetOutputIDs()[0])
+			exists["$.noop1"] = true
+		} else if op.ID() == "$.fake" {
+			require.Equal(t, 0, len(ops[2].GetOutputIDs()))
+			exists["$.fake"] = true
+		}
+	}
+	require.Equal(t, true, exists["$.noop"])
+	require.Equal(t, true, exists["$.noop1"])
+	require.Equal(t, true, exists["$.fake"])
```
Comment (djaglowski) [inline agent/builder_test.go:85]: Nit: `require.True(t, exists["$.noop"])`

File: agent/builder_test.go [hunk 2]
```diff
@@ -36,6 +60,29 @@ func TestBuildAgentSuccess(t *testing.T) {
...
+
+	ops := agent.pipeline.Operators()
+	require.Equal(t, 3, len(ops))
+
+	exists := make(map[string]bool)
+
+	for _, op := range ops {
+		if op.ID() == "$.noop" {
+			require.Equal(t, 1, len(ops[0].GetOutputIDs()))
+			require.Equal(t, "$.noop1", ops[0].GetOutputIDs()[0])
```
Comment (djaglowski) [inline agent/builder_test.go:72]:
```suggestion
			require.Equal(t, 1, len(op.GetOutputIDs()))
			require.Equal(t, "$.noop1", op.GetOutputIDs()[0])
```

File: agent/builder_test.go [hunk 3]
```diff
@@ -36,6 +60,29 @@ func TestBuildAgentSuccess(t *testing.T) {
...
+			exists["$.noop"] = true
+		} else if op.ID() == "$.noop1" {
+			require.Equal(t, 1, len(ops[1].GetOutputIDs()))
+			require.Equal(t, "$.fake", ops[1].GetOutputIDs()[0])
```
Comment (djaglowski) [inline agent/builder_test.go:76]:
```suggestion
			require.Equal(t, 1, len(op.GetOutputIDs()))
			require.Equal(t, "$.fake", op.GetOutputIDs()[0])
```

File: agent/builder_test.go [hunk 4]
```diff
@@ -36,6 +60,29 @@ func TestBuildAgentSuccess(t *testing.T) {
...
+			exists["$.noop1"] = true
+		} else if op.ID() == "$.fake" {
+			require.Equal(t, 0, len(ops[2].GetOutputIDs()))
```
Comment (djaglowski) [inline agent/builder_test.go:79]:
```suggestion
			require.Equal(t, 0, len(op.GetOutputIDs()))
```

File: pipeline/config.go [hunk 5]
```diff
@@ -38,6 +38,12 @@ func (c Config) BuildOperators(bc operator.BuildContext) ([]operator.Operator, e
 		}
 		operators = append(operators, op...)
 	}
+
+	if defaultOperator != nil {
+		bc.DefaultOutputIDs = []string{defaultOperator.ID()}
```
Comment (djaglowski) [inline pipeline/config.go:43]: BuildContext is not used after this point, so this line can be removed.

File: pipeline/config.go [hunk 6]
```diff
@@ -38,6 +38,12 @@ func (c Config) BuildOperators(bc operator.BuildContext) ([]operator.Operator, e
 		}
 		operators = append(operators, op...)
 	}
+
+	if defaultOperator != nil {
```
Comment (djaglowski) [inline pipeline/config.go:42]: We should also check whether the last operator can output. Otherwise, appending the default operator will have no effect other than inserting an orphaned node into the graph.

```suggestion
	if defaultOperator != nil && operators[len(operators)-1].CanOutput() {
```

**Review by djaglowski — CHANGES_REQUESTED** [review]

File: pipeline/config.go (hunk 5 above)
Comment (Mrod1598) [reply pipeline/config.go:43]: fixed

File: pipeline/config.go (hunk 6 above)
Comment (Mrod1598) [reply pipeline/config.go:42]: Added

File: agent/builder_test.go (hunk 4 above)
Comment (Mrod1598) [reply agent/builder_test.go:79]: Changed

File: agent/builder_test.go (hunk 3 above)
Comment (Mrod1598) [reply agent/builder_test.go:76]: Changed

File: agent/builder_test.go (hunk 2 above)
Comment (Mrod1598) [reply agent/builder_test.go:72]: Changed

File: agent/builder_test.go (hunk 1 above)
Comment (Mrod1598) [reply agent/builder_test.go:85]: Changed

**Comment by rockb1017** [comment]
awesome. great the root cause is already figured out! thank you!

**Review by djaglowski — APPROVED** [review]
LGTM. Thanks @Mrod1598!
